// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: storeservice.proto

package storeservice

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddFabricRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount float32 `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Cost   float32 `protobuf:"fixed32,3,opt,name=cost,proto3" json:"cost,omitempty"`
}

func (x *AddFabricRequest) Reset() {
	*x = AddFabricRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFabricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFabricRequest) ProtoMessage() {}

func (x *AddFabricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storeservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFabricRequest.ProtoReflect.Descriptor instead.
func (*AddFabricRequest) Descriptor() ([]byte, []int) {
	return file_storeservice_proto_rawDescGZIP(), []int{0}
}

func (x *AddFabricRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddFabricRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AddFabricRequest) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type AddFabricResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddFabricResponse) Reset() {
	*x = AddFabricResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFabricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFabricResponse) ProtoMessage() {}

func (x *AddFabricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storeservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFabricResponse.ProtoReflect.Descriptor instead.
func (*AddFabricResponse) Descriptor() ([]byte, []int) {
	return file_storeservice_proto_rawDescGZIP(), []int{1}
}

func (x *AddFabricResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateFabricRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount float32 `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Cost   float32 `protobuf:"fixed32,4,opt,name=cost,proto3" json:"cost,omitempty"`
}

func (x *UpdateFabricRequest) Reset() {
	*x = UpdateFabricRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFabricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFabricRequest) ProtoMessage() {}

func (x *UpdateFabricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storeservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFabricRequest.ProtoReflect.Descriptor instead.
func (*UpdateFabricRequest) Descriptor() ([]byte, []int) {
	return file_storeservice_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateFabricRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFabricRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFabricRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateFabricRequest) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type FabricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fabrics []*FabricsResponse_FabricResponse `protobuf:"bytes,1,rep,name=fabrics,proto3" json:"fabrics,omitempty"`
}

func (x *FabricsResponse) Reset() {
	*x = FabricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FabricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FabricsResponse) ProtoMessage() {}

func (x *FabricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storeservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FabricsResponse.ProtoReflect.Descriptor instead.
func (*FabricsResponse) Descriptor() ([]byte, []int) {
	return file_storeservice_proto_rawDescGZIP(), []int{3}
}

func (x *FabricsResponse) GetFabrics() []*FabricsResponse_FabricResponse {
	if x != nil {
		return x.Fabrics
	}
	return nil
}

type FabricsResponse_FabricResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FabricId string  `protobuf:"bytes,1,opt,name=fabric_id,json=fabricId,proto3" json:"fabric_id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount   float32 `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Cost     float32 `protobuf:"fixed32,4,opt,name=cost,proto3" json:"cost,omitempty"`
}

func (x *FabricsResponse_FabricResponse) Reset() {
	*x = FabricsResponse_FabricResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FabricsResponse_FabricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FabricsResponse_FabricResponse) ProtoMessage() {}

func (x *FabricsResponse_FabricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storeservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FabricsResponse_FabricResponse.ProtoReflect.Descriptor instead.
func (*FabricsResponse_FabricResponse) Descriptor() ([]byte, []int) {
	return file_storeservice_proto_rawDescGZIP(), []int{3, 0}
}

func (x *FabricsResponse_FabricResponse) GetFabricId() string {
	if x != nil {
		return x.FabricId
	}
	return ""
}

func (x *FabricsResponse_FabricResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FabricsResponse_FabricResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FabricsResponse_FabricResponse) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

var File_storeservice_proto protoreflect.FileDescriptor

var file_storeservice_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a,
	0x10, 0x41, 0x64, 0x64, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x63, 0x6f, 0x73,
	0x74, 0x22, 0x23, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x65, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x22, 0xc8, 0x01,
	0x0a, 0x0f, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x46, 0x0a, 0x07, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x07, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x6d, 0x0a, 0x0e, 0x46, 0x61, 0x62,
	0x72, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x61, 0x62, 0x72, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x32, 0xbb, 0x02, 0x0a, 0x0c, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x09, 0x41, 0x64, 0x64,
	0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x12, 0x1e, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x22,
	0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x3a,
	0x01, 0x2a, 0x12, 0x64, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x61, 0x62, 0x72,
	0x69, 0x63, 0x12, 0x21, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x19, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x13, 0x1a, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x66,
	0x61, 0x62, 0x72, 0x69, 0x63, 0x3a, 0x01, 0x2a, 0x12, 0x5c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x46,
	0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1d,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x61,
	0x62, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x66,
	0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x3b, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_storeservice_proto_rawDescOnce sync.Once
	file_storeservice_proto_rawDescData = file_storeservice_proto_rawDesc
)

func file_storeservice_proto_rawDescGZIP() []byte {
	file_storeservice_proto_rawDescOnce.Do(func() {
		file_storeservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_storeservice_proto_rawDescData)
	})
	return file_storeservice_proto_rawDescData
}

var file_storeservice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_storeservice_proto_goTypes = []interface{}{
	(*AddFabricRequest)(nil),               // 0: storeservice.AddFabricRequest
	(*AddFabricResponse)(nil),              // 1: storeservice.AddFabricResponse
	(*UpdateFabricRequest)(nil),            // 2: storeservice.UpdateFabricRequest
	(*FabricsResponse)(nil),                // 3: storeservice.FabricsResponse
	(*FabricsResponse_FabricResponse)(nil), // 4: storeservice.FabricsResponse.FabricResponse
	(*empty.Empty)(nil),                    // 5: google.protobuf.Empty
}
var file_storeservice_proto_depIdxs = []int32{
	4, // 0: storeservice.FabricsResponse.fabrics:type_name -> storeservice.FabricsResponse.FabricResponse
	0, // 1: storeservice.StoreService.AddFabric:input_type -> storeservice.AddFabricRequest
	2, // 2: storeservice.StoreService.UpdateFabric:input_type -> storeservice.UpdateFabricRequest
	5, // 3: storeservice.StoreService.GetFabrics:input_type -> google.protobuf.Empty
	1, // 4: storeservice.StoreService.AddFabric:output_type -> storeservice.AddFabricResponse
	5, // 5: storeservice.StoreService.UpdateFabric:output_type -> google.protobuf.Empty
	3, // 6: storeservice.StoreService.GetFabrics:output_type -> storeservice.FabricsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_storeservice_proto_init() }
func file_storeservice_proto_init() {
	if File_storeservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storeservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFabricRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFabricResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFabricRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FabricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FabricsResponse_FabricResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storeservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storeservice_proto_goTypes,
		DependencyIndexes: file_storeservice_proto_depIdxs,
		MessageInfos:      file_storeservice_proto_msgTypes,
	}.Build()
	File_storeservice_proto = out.File
	file_storeservice_proto_rawDesc = nil
	file_storeservice_proto_goTypes = nil
	file_storeservice_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreServiceClient interface {
	AddFabric(ctx context.Context, in *AddFabricRequest, opts ...grpc.CallOption) (*AddFabricResponse, error)
	UpdateFabric(ctx context.Context, in *UpdateFabricRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetFabrics(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FabricsResponse, error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) AddFabric(ctx context.Context, in *AddFabricRequest, opts ...grpc.CallOption) (*AddFabricResponse, error) {
	out := new(AddFabricResponse)
	err := c.cc.Invoke(ctx, "/storeservice.StoreService/AddFabric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) UpdateFabric(ctx context.Context, in *UpdateFabricRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/storeservice.StoreService/UpdateFabric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetFabrics(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FabricsResponse, error) {
	out := new(FabricsResponse)
	err := c.cc.Invoke(ctx, "/storeservice.StoreService/GetFabrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
type StoreServiceServer interface {
	AddFabric(context.Context, *AddFabricRequest) (*AddFabricResponse, error)
	UpdateFabric(context.Context, *UpdateFabricRequest) (*empty.Empty, error)
	GetFabrics(context.Context, *empty.Empty) (*FabricsResponse, error)
}

// UnimplementedStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServiceServer struct {
}

func (*UnimplementedStoreServiceServer) AddFabric(context.Context, *AddFabricRequest) (*AddFabricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFabric not implemented")
}
func (*UnimplementedStoreServiceServer) UpdateFabric(context.Context, *UpdateFabricRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFabric not implemented")
}
func (*UnimplementedStoreServiceServer) GetFabrics(context.Context, *empty.Empty) (*FabricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFabrics not implemented")
}

func RegisterStoreServiceServer(s *grpc.Server, srv StoreServiceServer) {
	s.RegisterService(&_StoreService_serviceDesc, srv)
}

func _StoreService_AddFabric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFabricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).AddFabric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storeservice.StoreService/AddFabric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).AddFabric(ctx, req.(*AddFabricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_UpdateFabric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFabricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).UpdateFabric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storeservice.StoreService/UpdateFabric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).UpdateFabric(ctx, req.(*UpdateFabricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetFabrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetFabrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storeservice.StoreService/GetFabrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetFabrics(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storeservice.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFabric",
			Handler:    _StoreService_AddFabric_Handler,
		},
		{
			MethodName: "UpdateFabric",
			Handler:    _StoreService_UpdateFabric_Handler,
		},
		{
			MethodName: "GetFabrics",
			Handler:    _StoreService_GetFabrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storeservice.proto",
}
